version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: future_designer_api 
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]